import { assertMockDatabaseIntegrity } from "./integrity";
import type { MockDatabaseTables, TableDefinition } from "./types";

export const tableDefinitions: Record<
  keyof MockDatabaseTables,
  TableDefinition
> = {
  roles: {
    description: "Danh sÃ¡ch role cá»§a há»‡ thá»‘ng",
    primaryKey: "id",
    columns: ["id", "code", "name"],
  },
  users: {
    description: "TÃ i khoáº£n dÃ¹ng chung cho má»i role",
    primaryKey: "id",
    columns: [
      "id",
      "roleId",
      "fullName",
      "email",
      "phone",
      "avatarUrl",
      "status",
    ],
  },
  branches: {
    description: "Chi nhÃ¡nh thÆ° viá»‡n hoáº·c khu lÆ°u trá»¯",
    primaryKey: "id",
    columns: ["id", "name", "campus", "address"],
  },
  students: {
    description: "Há»“ sÆ¡ nghiá»‡p vá»¥ cá»§a sinh viÃªn",
    primaryKey: "id",
    columns: [
      "id",
      "userId",
      "studentCode",
      "faculty",
      "program",
      "campus",
      "residence",
      "yearlyGoal",
      "booksRead",
      "currentBorrowLimit",
    ],
  },
  librarians: {
    description: "Há»“ sÆ¡ nghiá»‡p vá»¥ cá»§a thá»§ thÆ°",
    primaryKey: "id",
    columns: ["id", "userId", "employeeCode", "branchId", "shiftLabel"],
  },
  books: {
    description: "Äáº§u sÃ¡ch gá»‘c cá»§a thÆ° viá»‡n",
    primaryKey: "id",
    columns: [
      "id",
      "title",
      "author",
      "publisher",
      "year",
      "isbn",
      "summary",
      "coverUrl",
    ],
  },
  categories: {
    description: "Danh má»¥c phÃ¢n loáº¡i sÃ¡ch",
    primaryKey: "id",
    columns: ["id", "label"],
  },
  bookCategories: {
    description: "Báº£ng ná»‘i nhiá»u-nhiá»u giá»¯a sÃ¡ch vÃ  danh má»¥c",
    primaryKey: "id",
    columns: ["id", "bookId", "categoryId"],
  },
  bookCopies: {
    description: "Tá»«ng báº£n sao váº­t lÃ½ cá»§a sÃ¡ch trong kho",
    primaryKey: "id",
    columns: ["id", "bookId", "branchId", "copyCode", "shelfCode", "status"],
  },
  recommendations: {
    description: "Danh sÃ¡ch gá»£i Ã½ Ä‘áº§u sÃ¡ch theo ngÆ°á»i dÃ¹ng",
    primaryKey: "id",
    columns: ["id", "userId", "bookId", "rank"],
  },
  borrowRequests: {
    description: "Phiáº¿u workflow mÆ°á»£n sÃ¡ch hoáº·c gia háº¡n",
    primaryKey: "id",
    columns: [
      "id",
      "studentUserId",
      "bookId",
      "loanId",
      "branchId",
      "requestType",
      "workflowStatus",
      "createdLabel",
      "handledByUserId",
    ],
  },
  loans: {
    description: "Phiáº¿u mÆ°á»£n thá»±c táº¿ gáº¯n vá»›i báº£n sao sÃ¡ch",
    primaryKey: "id",
    columns: [
      "id",
      "studentUserId",
      "copyId",
      "bookId",
      "borrowedAt",
      "dueDate",
      "returnedAt",
      "status",
      "renewable",
      "fineAmount",
      "note",
    ],
  },
  loanHistories: {
    description: "Nháº­t kÃ½ giao dá»‹ch mÆ°á»£n tráº£",
    primaryKey: "id",
    columns: ["id", "loanId", "bookId", "eventType", "date", "note", "effectiveDueDate"],
  },
  notifications: {
    description: "ThÃ´ng bÃ¡o gá»­i tá»›i ngÆ°á»i dÃ¹ng",
    primaryKey: "id",
    columns: [
      "id",
      "userId",
      "type",
      "title",
      "message",
      "timeLabel",
      "amount",
      "relatedBookId",
      "relatedLoanId",
      "relatedRequestId",
    ],
  },
  activityLogs: {
    description: "Hoáº¡t Ä‘á»™ng gáº§n Ä‘Ã¢y trong dashboard thá»§ thÆ°",
    primaryKey: "id",
    columns: [
      "id",
      "branchId",
      "actorUserId",
      "title",
      "note",
      "timeLabel",
      "icon",
      "tone",
      "relatedBookId",
      "relatedLoanId",
      "relatedRequestId",
    ],
  },
  reportTemplates: {
    description: "Máº«u bÃ¡o cÃ¡o Jasper hoáº·c bÃ¡o cÃ¡o ná»™i bá»™",
    primaryKey: "id",
    columns: ["id", "title", "description", "badge", "icon"],
  },
  reportJobs: {
    description: "Lá»‹ch sá»­ hÃ ng Ä‘á»£i xuáº¥t file bÃ¡o cÃ¡o",
    primaryKey: "id",
    columns: [
      "id",
      "templateId",
      "fileName",
      "createdByUserId",
      "createdLabel",
      "statusLabel",
      "statusTone",
      "icon",
    ],
  },
};

export const demoSession = {
  studentUserId: "user-student-nam",
  librarianUserId: "user-librarian-minh",
  adminUserId: "user-admin-thao",
  branchId: "branch-central",
} as const;

export const mockDatabaseSeed: MockDatabaseTables = {
  roles: [
    { id: "role-student", code: "student", name: "Student" },
    { id: "role-librarian", code: "librarian", name: "Librarian" },
    { id: "role-admin", code: "admin", name: "Admin" },
  ],
  users: [
    {
      id: "user-student-nam",
      roleId: "role-student",
      fullName: "Nguyá»…n VÄƒn Nam",
      email: "sv123456@tdmu.edu.vn",
      phone: "0901234567",
      avatarUrl: "https://i.pravatar.cc/240?img=12",
      status: "active",
    },
    {
      id: "user-student-a",
      roleId: "role-student",
      fullName: "Nguyá»…n VÄƒn A",
      email: "nguyenvana@tdmu.edu.vn",
      phone: "0900000001",
      avatarUrl: "https://i.pravatar.cc/240?img=31",
      status: "active",
    },
    {
      id: "user-student-b",
      roleId: "role-student",
      fullName: "Tráº§n Thá»‹ B",
      email: "tranthib@tdmu.edu.vn",
      phone: "0900000002",
      avatarUrl: "https://i.pravatar.cc/240?img=32",
      status: "active",
    },
    {
      id: "user-student-le-b",
      roleId: "role-student",
      fullName: "LÃª Thá»‹ B",
      email: "lethib@tdmu.edu.vn",
      phone: "0900000003",
      avatarUrl: "https://i.pravatar.cc/240?img=33",
      status: "active",
    },
    {
      id: "user-student-tran-c",
      roleId: "role-student",
      fullName: "Tráº§n Minh C",
      email: "tranminhc@tdmu.edu.vn",
      phone: "0900000004",
      avatarUrl: "https://i.pravatar.cc/240?img=34",
      status: "active",
    },
    {
      id: "user-student-le-qd",
      roleId: "role-student",
      fullName: "LÃª Quá»‘c D",
      email: "lequocd@tdmu.edu.vn",
      phone: "0900000005",
      avatarUrl: "https://i.pravatar.cc/240?img=35",
      status: "active",
    },
    {
      id: "user-librarian-minh",
      roleId: "role-librarian",
      fullName: "Thá»§ thÆ° Minh",
      email: "librarian.minh@tdmu.edu.vn",
      phone: "0912345678",
      avatarUrl: "https://i.pravatar.cc/240?img=14",
      status: "active",
    },
    {
      id: "user-admin-thao",
      roleId: "role-admin",
      fullName: "Admin Tháº£o",
      email: "admin.thao@tdmu.edu.vn",
      phone: "0987654321",
      avatarUrl: "https://i.pravatar.cc/240?img=25",
      status: "active",
    },
  ],
  branches: [
    {
      id: "branch-central",
      name: "ThÆ° viá»‡n Trung tÃ¢m",
      campus: "tdmu HCM",
      address: "LÃ´ E2a-7, ÄÆ°á»ng D1, Khu CÃ´ng nghá»‡ cao, TP.HCM",
    },
  ],
  students: [
    {
      id: "student-1",
      userId: "user-student-nam",
      studentCode: "SV123456",
      faculty: "ChÃ­nh quy",
      program: "Ká»¹ thuáº­t pháº§n má»m",
      campus: "tdmu HCM",
      residence: "KTX Khu B",
      yearlyGoal: 20,
      booksRead: 12,
      currentBorrowLimit: 5,
    },
    {
      id: "student-2",
      userId: "user-student-a",
      studentCode: "SV2021001",
      faculty: "ChÃ­nh quy",
      program: "Ká»¹ thuáº­t pháº§n má»m",
      campus: "tdmu HCM",
      residence: "KTX Khu A",
      yearlyGoal: 18,
      booksRead: 9,
      currentBorrowLimit: 5,
    },
    {
      id: "student-3",
      userId: "user-student-b",
      studentCode: "SV20215678",
      faculty: "ChÃ­nh quy",
      program: "Há»‡ thá»‘ng thÃ´ng tin",
      campus: "tdmu HCM",
      residence: "NgoÃ¡ÂºÂ¡i trÃƒÂº",
      yearlyGoal: 16,
      booksRead: 7,
      currentBorrowLimit: 5,
    },
    {
      id: "student-4",
      userId: "user-student-le-b",
      studentCode: "SV2022450",
      faculty: "ChÃ­nh quy",
      program: "Kinh doanh quá»‘c táº¿",
      campus: "tdmu HCM",
      residence: "KTX Khu C",
      yearlyGoal: 14,
      booksRead: 5,
      currentBorrowLimit: 5,
    },
    {
      id: "student-5",
      userId: "user-student-tran-c",
      studentCode: "SV2020881",
      faculty: "ChÃ­nh quy",
      program: "Thiáº¿t káº¿ tráº£i nghiá»‡m",
      campus: "tdmu HCM",
      residence: "NgoÃ¡ÂºÂ¡i trÃƒÂº",
      yearlyGoal: 15,
      booksRead: 8,
      currentBorrowLimit: 5,
    },
    {
      id: "student-6",
      userId: "user-student-le-qd",
      studentCode: "SV2022552",
      faculty: "ChÃ­nh quy",
      program: "Khoa há»c dá»¯ liá»‡u",
      campus: "tdmu HCM",
      residence: "KTX Khu D",
      yearlyGoal: 20,
      booksRead: 11,
      currentBorrowLimit: 5,
    },
  ],
  librarians: [
    {
      id: "librarian-1",
      userId: "user-librarian-minh",
      employeeCode: "LIB102",
      branchId: "branch-central",
      shiftLabel: "Ca: SÃ¡ng",
    },
  ],
  books: [
    {
      id: "machine-learning-mo-rong",
      title: "Machine Learning Má»Ÿ Rá»™ng",
      author: "Tráº§n VÅ© HoÃ ng",
      publisher: "NXB Tráº»",
      year: 2023,
      isbn: "978-604-1-23456-7",
      summary:
        "Cuá»‘n sÃ¡ch há»‡ thá»‘ng hÃ³a cÃ¡c thuáº­t toÃ¡n machine learning hiá»‡n Ä‘áº¡i, tá»« ná»n táº£ng Ä‘áº¿n NLP vÃ  thá»‹ giÃ¡c mÃ¡y tÃ­nh.",
      coverUrl:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuDgqhCRzWoN5iEWQ2aq02NRndeKD7h_bCCvlp4TzTaC3RDqiMGqj7TyZGRdRjEuJCDNGQj9VDOML1ZMt_qk6SUkBKunIV9bqRUBV2hPJWONot5CKrrLNjC7jhMtLan-d17w-eyVD3AorOIlIPiEbhcFEGdtnNkmvJjBV_QW-G7Zph0cqB4IpMdFHJjXa6qT88AVhkRJtCG2LUVQIi2Y3UDHA9BGNwKcX02N_ieu9-HC5IvnfxihCezsPVRqy42GqcEJqzyVro4AHLsY",
    },
    {
      id: "clean-code",
      title: "Clean Code",
      author: "Robert C. Martin",
      publisher: "Pearson",
      year: 2019,
      isbn: "978-0-13-235088-4",
      summary:
        "TÃ i liá»‡u kinh Ä‘iá»ƒn vá» ká»¹ thuáº­t viáº¿t mÃ£ dá»… Ä‘á»c, dá»… báº£o trÃ¬ vÃ  cÃ³ cáº¥u trÃºc rÃµ rÃ ng.",
      coverUrl:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuBki8jg_20owJbI4qJ0tHX0ih8XCnIhU2iTIQf8_Px8S0145d8t5Z_gKg_qqCB_6wcakaoZx6hPsj0kXQ38iSh1aJtNUnj27t625cUSOM4MgUbb_g3PTNTfHzL4NuqjrT9EPfyuSo2A7WoMQoOq5FZN7rOoKQsf68Rz_HilzAH2MnWXMWWWn1fuuDLII-mqIYpx479T-tZPKnJD6h6IDkWpIk_-lqD_4MQHYvLzYqGH6u1y1i7jrkIU1KuDCSw4yVEnCwrD9-Up_zTF",
    },
    {
      id: "deep-learning-co-ban",
      title: "Deep Learning CÆ¡ Báº£n",
      author: "LÃª VÄƒn A",
      publisher: "ÄHQG TP.HCM",
      year: 2022,
      isbn: "978-604-73-9988-1",
      summary:
        "SÃ¡ch nháº­p mÃ´n deep learning vá»›i minh há»a trá»±c quan, perceptron, CNN vÃ  pipeline huáº¥n luyá»‡n mÃ´ hÃ¬nh.",
      coverUrl:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuALVfeTXqI8D74hjWIkHo_M5pWzQ-ldNMqoAb9VNmVuxUY7zzbt1B5i6sK6hOmvkSMkgMjdDQY1uApoBwg5MqdePBE7zcQwiOW6AziKVmGj96zLnaxfEkowDWdcNxKi6F26VvnTQxmMeHWncDjajaikjnrlwItWHAzHoojv4XFBlQ3dHCVR8vY0t0lfo5BIbX1MCeCehRj6LHTbWuHKpU4PFYVpto2yJK0LF6ViaQzm3tpOCebjfnsEpX-Kn1c1JN7IRh7U89oOMnSM",
    },
    {
      id: "vi-mach-ung-dung",
      title: "Vi Máº¡ch á»¨ng Dá»¥ng",
      author: "Nguyá»…n Thá»‹ B",
      publisher: "NXB Khoa há»c",
      year: 2021,
      isbn: "978-604-77-5544-3",
      summary:
        "Giá»›i thiá»‡u kiáº¿n trÃºc máº¡ch tÃ­ch há»£p, cÃ¡c á»©ng dá»¥ng IoT cÆ¡ báº£n vÃ  cÃ¡ch Ä‘á»c datasheet trong phÃ²ng lab.",
      coverUrl:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuDhymAGPhKxq27u917CUF18_X17IdUpv6s-UPT8H9s5hxrcpghK56Z4_qLLY4_o9LZ585Eg2xD49pTUnGrdJGwR03yIJvOR0zAImyk4RPW_iQZcVK6scFsl4rwsuyULBgtm8JvBwILiIdELwdzhH_N6j55dRc4DWWISi7tYkR2X5K3wJx8xyCmKUt2cQkY8RgdK6K8aJ0jiiSryMCVEvx9wZJVoxXxwpeE-Y7-fFsj5A6MMUnFt96xqsGnMSlFCkPwhbD3PY79eH5Kd",
    },
    {
      id: "du-lieu-lon",
      title: "Dá»¯ Liá»‡u Lá»›n",
      author: "Pháº¡m VÄƒn C",
      publisher: "NXB CNTT",
      year: 2024,
      isbn: "978-604-80-2200-0",
      summary:
        "KhÃ¡i quÃ¡t há»‡ sinh thÃ¡i dá»¯ liá»‡u lá»›n, pipeline ETL vÃ  cÃ¡c cÃ´ng cá»¥ phÃ¢n tÃ­ch dá»¯ liá»‡u á»Ÿ quy mÃ´ doanh nghiá»‡p.",
      coverUrl:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuCnbKbXjeMvcw1wtnyFEIWnQ_vr5rW4Y0ACKTtrCj7qUcLoXVfi5Qea6Oyaq-5wVSR6UxEAtY5k4PVZt2hkfZsDoh1Sh4C8i1NsrT0YFD10IZipxdcHlPhkeD5Y8-rqmuzJZH9S4_Awv3SFsQwzp2b07Fdnviq4SpLtzdwKNSw6gePbLtCrozca0ygzo8CyQK3sFaJ9lBdjEbX_ozg7UL28W-bw3aoAO6tYGwtYlVW1gwUa6H76D_mBY7roKH1DHx2AT_oUFTdJ2jS8",
    },
    {
      id: "design-patterns-modern-software",
      title: "Design Patterns in Modern Software",
      author: "Erich Gamma",
      publisher: "Addison-Wesley",
      year: 2020,
      isbn: "978-0-13-670235-1",
      summary:
        "CÃ¡c design pattern quen thuá»™c Ä‘Æ°á»£c diá»…n giáº£i theo cÃ¡ch Ã¡p dá»¥ng trong há»‡ thá»‘ng hiá»‡n Ä‘áº¡i.",
      coverUrl:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuATUTaSG6dkCsxW5OmUJqP3pWNt37EsvvlMr3U8SQfCxGrpvfJd_0A63Zd5Y9htb-7VF8Jtsf12Qa1akI-Yq6tGG_Ai77wEEaEcwkdwzkxkQs_i4cCcUMopft6g5c2EVzRGlE7584h77oJ73jEBEsUMhjzf26Vzt_zlUKrHhYoP41TpgA5-qUaSEszaM7jThNnOu1XrNMxaAFaXVyoIKhWW7xwnouSpgWJr5oQcMlcRZaaROLw2gFSlI65aTg3F3B_r-ryitYOEKukA",
    },
    {
      id: "elements-of-user-experience",
      title: "The Elements of User Experience",
      author: "Jesse James Garrett",
      publisher: "New Riders",
      year: 2018,
      isbn: "978-0-321-68368-7",
      summary:
        "Khung tÆ° duy kinh Ä‘iá»ƒn cho viá»‡c tá»• chá»©c tráº£i nghiá»‡m ngÆ°á»i dÃ¹ng, tá»« chiáº¿n lÆ°á»£c sáº£n pháº©m Ä‘áº¿n lá»›p giao diá»‡n.",
      coverUrl:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuBTVKI_ZId6u3dn9sQ6mou87jSDOiMoAKv41cY06ZGb5-XWnL_b8IkNHMqLYUI4LrSbjUJdpbLGba6_kmy5ztbeqosQNDUDU_rvzy_-UwhbCkKeGyzStk6HISblPsssifyxlo60iMlsJKSFBXNA2wIiuHIaF9dHoouQ38abH0RMp0UgoGLQq-RD2n6BJ4t1XxgUEEOfKGTl8Qvw-MlZbAOWRY6kujpcNB52HrGzyb5gzV9FaAbcWdVo75l0Vx2wBO2f6bv9GeV3WE0q",
    },
  ],
  categories: [
    { id: "cat-ai", label: "AI" },
    { id: "cat-data", label: "Dá»¯ liá»‡u" },
    { id: "cat-software", label: "Software" },
    { id: "cat-architecture", label: "Architecture" },
    { id: "cat-design", label: "Design" },
    { id: "cat-ux", label: "UX" },
    { id: "cat-hardware", label: "Pháº§n cá»©ng" },
    { id: "cat-cloud", label: "Cloud" },
    { id: "cat-product", label: "Product" },
  ],
  bookCategories: [
    {
      id: "book-cat-1",
      bookId: "machine-learning-mo-rong",
      categoryId: "cat-ai",
    },
    {
      id: "book-cat-2",
      bookId: "machine-learning-mo-rong",
      categoryId: "cat-data",
    },
    { id: "book-cat-3", bookId: "clean-code", categoryId: "cat-software" },
    { id: "book-cat-4", bookId: "deep-learning-co-ban", categoryId: "cat-ai" },
    {
      id: "book-cat-5",
      bookId: "deep-learning-co-ban",
      categoryId: "cat-data",
    },
    {
      id: "book-cat-6",
      bookId: "vi-mach-ung-dung",
      categoryId: "cat-hardware",
    },
    { id: "book-cat-7", bookId: "du-lieu-lon", categoryId: "cat-data" },
    { id: "book-cat-8", bookId: "du-lieu-lon", categoryId: "cat-cloud" },
    {
      id: "book-cat-9",
      bookId: "design-patterns-modern-software",
      categoryId: "cat-architecture",
    },
    {
      id: "book-cat-10",
      bookId: "design-patterns-modern-software",
      categoryId: "cat-design",
    },
    {
      id: "book-cat-11",
      bookId: "elements-of-user-experience",
      categoryId: "cat-ux",
    },
    {
      id: "book-cat-12",
      bookId: "elements-of-user-experience",
      categoryId: "cat-product",
    },
  ],
  bookCopies: [
    {
      id: "copy-1",
      bookId: "vi-mach-ung-dung",
      branchId: "branch-central",
      copyCode: "PHI-101-C",
      shelfCode: "Ká»‡ B2-12",
      status: "damaged",
    },
    {
      id: "copy-2",
      bookId: "machine-learning-mo-rong",
      branchId: "branch-central",
      copyCode: "ML-002-A",
      shelfCode: "Ká»‡ A2-01",
      status: "borrowed",
    },
    {
      id: "copy-3",
      bookId: "clean-code",
      branchId: "branch-central",
      copyCode: "ECO-001-A",
      shelfCode: "Ká»‡ A3-02",
      status: "available",
    },
    {
      id: "copy-4",
      bookId: "clean-code",
      branchId: "branch-central",
      copyCode: "CC-004-B",
      shelfCode: "Ká»‡ B1-03",
      status: "available",
    },
    {
      id: "copy-5",
      bookId: "clean-code",
      branchId: "branch-central",
      copyCode: "CC-004-C",
      shelfCode: "Ká»‡ B1-04",
      status: "available",
    },
    {
      id: "copy-6",
      bookId: "clean-code",
      branchId: "branch-central",
      copyCode: "CC-004-D",
      shelfCode: "Ká»‡ B1-05",
      status: "borrowed",
    },
    {
      id: "copy-7",
      bookId: "deep-learning-co-ban",
      branchId: "branch-central",
      copyCode: "DL-003-A",
      shelfCode: "Ká»‡ A5-02",
      status: "available",
    },
    {
      id: "copy-8",
      bookId: "vi-mach-ung-dung",
      branchId: "branch-central",
      copyCode: "VM-001-A",
      shelfCode: "Ká»‡ D4-01",
      status: "available",
    },
    {
      id: "copy-9",
      bookId: "vi-mach-ung-dung",
      branchId: "branch-central",
      copyCode: "VM-001-B",
      shelfCode: "Ká»‡ D4-02",
      status: "available",
    },
    {
      id: "copy-10",
      bookId: "vi-mach-ung-dung",
      branchId: "branch-central",
      copyCode: "VM-001-C",
      shelfCode: "Ká»‡ D4-03",
      status: "borrowed",
    },
    {
      id: "copy-11",
      bookId: "du-lieu-lon",
      branchId: "branch-central",
      copyCode: "DLL-007-A",
      shelfCode: "Ká»‡ B7-01",
      status: "borrowed",
    },
    {
      id: "copy-12",
      bookId: "design-patterns-modern-software",
      branchId: "branch-central",
      copyCode: "COM-204-B",
      shelfCode: "Ká»‡ C1-05",
      status: "borrowed",
    },
    {
      id: "copy-13",
      bookId: "design-patterns-modern-software",
      branchId: "branch-central",
      copyCode: "DP-201-C",
      shelfCode: "Ká»‡ C2-02",
      status: "available",
    },
    {
      id: "copy-14",
      bookId: "elements-of-user-experience",
      branchId: "branch-central",
      copyCode: "UX-001-A",
      shelfCode: "Ká»‡ E3-01",
      status: "borrowed",
    },
    {
      id: "copy-15",
      bookId: "elements-of-user-experience",
      branchId: "branch-central",
      copyCode: "UX-001-B",
      shelfCode: "Ká»‡ E3-02",
      status: "available",
    },
    {
      id: "copy-16",
      bookId: "elements-of-user-experience",
      branchId: "branch-central",
      copyCode: "UX-001-C",
      shelfCode: "Ká»‡ E3-03",
      status: "available",
    },
    {
      id: "copy-17",
      bookId: "elements-of-user-experience",
      branchId: "branch-central",
      copyCode: "UX-001-D",
      shelfCode: "Ká»‡ E3-04",
      status: "available",
    },
    {
      id: "copy-18",
      bookId: "elements-of-user-experience",
      branchId: "branch-central",
      copyCode: "UX-001-E",
      shelfCode: "Ká»‡ E3-05",
      status: "available",
    },
    {
      id: "copy-19",
      bookId: "machine-learning-mo-rong",
      branchId: "branch-central",
      copyCode: "ML-002-B",
      shelfCode: "KÃ¡Â»â€¡ A2-02",
      status: "borrowed",
    },
  ],
  recommendations: [
    {
      id: "rec-1",
      userId: "user-student-nam",
      bookId: "design-patterns-modern-software",
      rank: 1,
    },
    {
      id: "rec-2",
      userId: "user-student-nam",
      bookId: "elements-of-user-experience",
      rank: 2,
    },
    {
      id: "rec-3",
      userId: "user-student-nam",
      bookId: "machine-learning-mo-rong",
      rank: 3,
    },
    { id: "rec-4", userId: "user-student-nam", bookId: "clean-code", rank: 4 },
  ],
  borrowRequests: [
    {
      id: "request-1",
      studentUserId: "user-student-nam",
      bookId: "machine-learning-mo-rong",
      branchId: "branch-central",
      requestType: "borrow",
      workflowStatus: "pending",
      createdLabel: "2 phút trước",
      handledByUserId: "user-librarian-minh",
    },
    {
      id: "request-2",
      studentUserId: "user-student-le-b",
      bookId: "design-patterns-modern-software",
      branchId: "branch-central",
      requestType: "borrow",
      workflowStatus: "processing",
      createdLabel: "15 phút trước",
      handledByUserId: "user-librarian-minh",
    },
    {
      id: "request-3",
      studentUserId: "user-student-tran-c",
      bookId: "elements-of-user-experience",
      branchId: "branch-central",
      requestType: "borrow",
      workflowStatus: "staging",
      createdLabel: "1 giờ trước",
      handledByUserId: "user-librarian-minh",
    },
    {
      id: "request-4",
      studentUserId: "user-student-nam",
      bookId: "elements-of-user-experience",
      loanId: "loan-1",
      branchId: "branch-central",
      requestType: "renew",
      workflowStatus: "pending",
      createdLabel: "8 phút trước",
      handledByUserId: "user-librarian-minh",
    },
    {
      id: "request-5",
      studentUserId: "user-student-le-qd",
      bookId: "vi-mach-ung-dung",
      loanId: "loan-8",
      branchId: "branch-central",
      requestType: "renew",
      workflowStatus: "processing",
      createdLabel: "40 phút trước",
      handledByUserId: "user-librarian-minh",
    },
  ],
  loans: [
    {
      id: "loan-1",
      studentUserId: "user-student-nam",
      copyId: "copy-14",
      bookId: "elements-of-user-experience",
      borrowedAt: "08/10/2026",
      dueDate: "15/10/2026",
      status: "due-soon",
      renewable: true,
      note: "CÃ²n 2 ngÃ y",
    },
    {
      id: "loan-2",
      studentUserId: "user-student-nam",
      copyId: "copy-11",
      bookId: "du-lieu-lon",
      borrowedAt: "28/09/2026",
      dueDate: "11/10/2026",
      status: "overdue",
      renewable: false,
      fineAmount: 5000,
      note: "QuÃ¡ háº¡n 3 ngÃ y",
    },
    {
      id: "loan-3",
      studentUserId: "user-student-nam",
      copyId: "copy-2",
      bookId: "machine-learning-mo-rong",
      borrowedAt: "12/10/2026",
      dueDate: "22/10/2026",
      status: "borrowed",
      renewable: true,
    },
    {
      id: "loan-4",
      studentUserId: "user-student-nam",
      copyId: "copy-4",
      bookId: "clean-code",
      borrowedAt: "20/09/2026",
      dueDate: "06/10/2026",
      returnedAt: "06/10/2026",
      status: "returned",
      renewable: false,
    },
    {
      id: "loan-5",
      studentUserId: "user-student-a",
      copyId: "copy-6",
      bookId: "clean-code",
      borrowedAt: "05/10/2026",
      dueDate: "10/10/2026",
      status: "overdue",
      renewable: false,
      fineAmount: 50000,
      note: "QuÃ¡ háº¡n 5 ngÃ y",
    },
    {
      id: "loan-6",
      studentUserId: "user-student-b",
      copyId: "copy-19",
      bookId: "machine-learning-mo-rong",
      borrowedAt: "07/10/2026",
      dueDate: "12/10/2026",
      status: "overdue",
      renewable: false,
      fineAmount: 30000,
      note: "QuÃ¡ háº¡n 3 ngÃ y",
    },
    {
      id: "loan-7",
      studentUserId: "user-student-tran-c",
      copyId: "copy-12",
      bookId: "design-patterns-modern-software",
      borrowedAt: "10/10/2026",
      dueDate: "16/10/2026",
      status: "due-soon",
      renewable: true,
      note: "Ã„ÂÃ¡ÂºÂ¿n hÃ¡ÂºÂ¡n hÃƒÂ´m nay",
    },
    {
      id: "loan-8",
      studentUserId: "user-student-le-qd",
      copyId: "copy-10",
      bookId: "vi-mach-ung-dung",
      borrowedAt: "09/10/2026",
      dueDate: "16/10/2026",
      status: "due-soon",
      renewable: true,
      note: "Ã„ÂÃ¡ÂºÂ¿n hÃ¡ÂºÂ¡n hÃƒÂ´m nay",
    },
  ],
  loanHistories: [
    {
      id: "history-1",
      loanId: "loan-3",
      bookId: "machine-learning-mo-rong",
      eventType: "borrowed",
      date: "12 Thg 10, 2026",
      note: "Hạn trả: 22 Thg 10, 2026",
      effectiveDueDate: "22/10/2026",
    },
    {
      id: "history-2",
      loanId: "loan-4",
      bookId: "clean-code",
      eventType: "returned",
      date: "06 Thg 10, 2026",
      note: "Đã trả tại quầy số 2",
    },
    {
      id: "history-3",
      loanId: "loan-1",
      bookId: "elements-of-user-experience",
      eventType: "renewed",
      date: "08 Thg 10, 2026",
      note: "Hạn trả mới: 15 Thg 10, 2026",
      effectiveDueDate: "15/10/2026",
    },
    {
      id: "history-4",
      loanId: "loan-2",
      bookId: "du-lieu-lon",
      eventType: "borrowed",
      date: "28 Thg 09, 2026",
      note: "Hạn trả: 11 Thg 10, 2026",
      effectiveDueDate: "11/10/2026",
    },
  ],
  notifications: [
    {
      id: "notif-1",
      userId: "user-student-nam",
      type: "success",
      title: "Yêu cầu mượn thành công",
      message:
        'Cuốn "The Elements of User Experience" đã sẵn sàng tại quầy số 2. Vui lòng đến nhận trước 17:00.',
      timeLabel: "Vừa xong",
      relatedBookId: "elements-of-user-experience",
      relatedLoanId: "loan-1",
    },
    {
      id: "notif-2",
      userId: "user-student-nam",
      type: "warning",
      title: "Sách sắp đến hạn",
      message:
        'Cuốn "Machine Learning Mở Rộng" sẽ đến hạn trả vào ngày mai. Bạn có thể gửi yêu cầu gia hạn ngay trong ứng dụng.',
      timeLabel: "2 giờ trước",
      relatedBookId: "machine-learning-mo-rong",
      relatedLoanId: "loan-3",
    },
    {
      id: "notif-3",
      userId: "user-student-nam",
      type: "danger",
      title: "Bạn có khoản phạt quá hạn",
      message:
        "Vui lòng thanh toán tại quầy thủ thư để tiếp tục sử dụng dịch vụ mượn sách và tránh phát sinh thêm phụ phí.",
      timeLabel: "Hôm qua",
      amount: "5.000đ",
      relatedBookId: "du-lieu-lon",
      relatedLoanId: "loan-2",
    },
    {
      id: "notif-4",
      userId: "user-student-nam",
      type: "info",
      title: "Thư viện nghỉ lễ",
      message:
        "Thư viện sẽ đóng cửa từ ngày 01/05 đến 03/05. Các khoản mượn trong thời gian này sẽ được gia hạn tự động.",
      timeLabel: "3 ngày trước",
    },
  ],
  activityLogs: [
    {
      id: "activity-1",
      branchId: "branch-central",
      actorUserId: "user-librarian-minh",
      title: "Nguyễn Văn A - Mượn thành công",
      note: "Clean Code",
      timeLabel: "Vừa xong",
      icon: "check-circle",
      tone: "primary",
      relatedBookId: "clean-code",
      relatedLoanId: "loan-5",
    },
    {
      id: "activity-2",
      branchId: "branch-central",
      actorUserId: "user-librarian-minh",
      title: "Cập nhật trạng thái Camunda",
      note: "Tiến trình xét duyệt tự động hoàn tất",
      timeLabel: "5 phút trước",
      icon: "history",
      tone: "warning",
    },
    {
      id: "activity-3",
      branchId: "branch-central",
      actorUserId: "user-librarian-minh",
      title: "Trần Thị B - Phạt quá hạn",
      note: "Machine Learning Mở Rộng (Quá hạn 3 ngày)",
      timeLabel: "15 phút trước",
      icon: "warning",
      tone: "danger",
      relatedBookId: "machine-learning-mo-rong",
      relatedLoanId: "loan-6",
    },
  ],
  reportTemplates: [
    {
      id: "report-template-1",
      title: "BÃ¡o cÃ¡o mÆ°á»£n tráº£",
      description: "Thá»‘ng kÃª chi tiáº¿t sÃ¡ch Ä‘Æ°á»£c mÆ°á»£n vÃ  tráº£ láº¡i trong ká»³.",
      badge: "HÃ ng ngÃ y",
      icon: "history",
    },
    {
      id: "report-template-2",
      title: "BÃ¡o cÃ¡o quÃ¡ háº¡n",
      description:
        "Danh sÃ¡ch báº¡n Ä‘á»c giá»¯ tÃ i liá»‡u vÆ°á»£t quÃ¡ thá»i gian quy Ä‘á»‹nh.",
      badge: "Æ¯u tiÃªn cao",
      icon: "warning",
    },
    {
      id: "report-template-3",
      title: "Thá»‘ng kÃª tiá»n pháº¡t",
      description: "Tá»•ng há»£p cÃ¡c khoáº£n thu tá»« viá»‡c pháº¡t trá»… háº¡n vÃ  Ä‘á»n bÃ¹.",
      badge: "TÃ i chÃ­nh",
      icon: "money",
    },
    {
      id: "report-template-4",
      title: "BÃ¡o cÃ¡o lÆ°u thÃ´ng",
      description: "ÄÃ¡nh giÃ¡ táº§n suáº¥t sá»­ dá»¥ng cá»§a cÃ¡c Ä‘áº§u má»¥c tÃ i liá»‡u.",
      badge: "PhÃ¢n tÃ­ch",
      icon: "report",
    },
  ],
  reportJobs: [
    {
      id: "report-job-1",
      templateId: "report-template-4",
      fileName: "Bao_cao_luu_thong_T10_2023.xlsx",
      createdByUserId: "user-admin-thao",
      createdLabel: "HÃ´m nay, 14:30",
      statusLabel: "HoÃ n thÃ nh",
      statusTone: "success",
      icon: "report",
    },
    {
      id: "report-job-2",
      templateId: "report-template-2",
      fileName: "Bao_cao_qua_han_W42.pdf",
      createdByUserId: "user-librarian-minh",
      createdLabel: "HÃ´m qua, 09:15",
      statusLabel: "HoÃ n thÃ nh",
      statusTone: "success",
      icon: "warning",
    },
    {
      id: "report-job-3",
      templateId: "report-template-3",
      fileName: "Thong_ke_tien_phat_Q3.xlsx",
      createdByUserId: "user-admin-thao",
      createdLabel: "Äang xá»­ lÃ½...",
      statusLabel: "Äang táº¡o",
      statusTone: "warning",
      icon: "history",
    },
  ],
};

function cloneMockDatabase(source: MockDatabaseTables): MockDatabaseTables {
  if (typeof globalThis.structuredClone === "function") {
    return globalThis.structuredClone(source);
  }

  return JSON.parse(JSON.stringify(source)) as MockDatabaseTables;
}

export let mockDatabase: MockDatabaseTables =
  cloneMockDatabase(mockDatabaseSeed);

assertMockDatabaseIntegrity(mockDatabaseSeed);
assertMockDatabaseIntegrity(mockDatabase);

export function createMockDatabaseSnapshot() {
  return cloneMockDatabase(mockDatabaseSeed);
}

export function resetMockDatabase() {
  mockDatabase = createMockDatabaseSnapshot();
  assertMockDatabaseIntegrity(mockDatabase);
  return mockDatabase;
}

